# Site settings
title: Emil Mork
email: emil.a.mork@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Developer from Norway.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://emilmork.net" # the base hostname & protocol for your site
twitter_username: emil_mork
github_username:  emilmork

# Build settings
markdown: kramdown
